server:
  port: 1234
  tomcat:
    uri-encoding: UTF-8
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  metrics:
    data:
      repository:
        autotime:
          percentiles: 0.5,0.95
    web:
      server:
        request:
          autotime:
            percentiles: 0.5,0.95